### PR TITLE
Migrated to .NET 6 and some other improvements

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by CodeMazeBlog** [comment]
Hey Ayub, please don't create PR's on random repositories. We have a tight schedule and we don't have time to process each PR. It's perfectly fine to work on your forks though if you want to improve your skills.

**Comment by ghost** [comment]
Okay, Okay, Okay!
Sorry to waste your time closing this PR. 

Just to know, submitting pull requests is a non-destructive operation. You can easily skip or close it without any reason. It's your right. Okay. But it isn't true, to prevent GitHub users from creating pull requests in a public repository. You do not even have any description or contribution guidelines in your repo. How would people know they shouldn't send PR.

In addition, I'm the one who wasted his time. Why are you getting upset?
Even if I made a mistake, which is possible since I'm not infallible, that's no way to speak!

**Comment by CodeMazeBlog** [comment]
You must have misunderstood my message. I've politely asked you not to open PRs where you're not supposed to. It seems like you're the one getting upset. 

Either way, my point is that there are a lot of repositories out there looking for someone to contribute and help. These repositories are not meant to be changed through PRs and we like to keep them clean. My message to you was also information that we won't have time to look at your PRs or anyone else's for that matter on the repositories we haven't explicitly asked for people to contribute to.

As for your pre-edited message: yes, everyone *can* create a PR, but that doesn't mean that they *should* create it. I'm familiar with the documentation, but thanks. And there are ways to prevent people from creating PRs, but that's not something we want to do and that's why I've sent you a _polite_ message not to do that.

Cheers,
Vladimir

**Comment by Duelbat** [comment]
What crap email is this ?
I am unsubscribing!

Kind regards
Luke Vincent

**Pull request closed without merging**
